spring:
  datasource:
    url: jdbc:h2:mem:sb2025
    username: sb2025
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true